### ISSUE TITLE
Date / month error on import

### ISSUE THREAD

**Issue by abhijit86k** [abhijit86k/PayTMFastTag-FuelIO-Translator#4]
Checkout/merge my automation branch:
@abhijit86k/PayTMFastTag-FuelIO-Translator@b6514ccb0e44a2d3367dceeef4a76ac1821f2473

then run:
`./translate.py --infile PayTM_Wallet_Txn_History_Sample2.csv --outfile FuelIOSample-vehicle-3-sync.csv 
`

The resulting file should have entries for 10 Jan, instead it has for 10th October :)

**Comment by budhadityabanerjee** [comment]
Opened https://github.com/abhijit86k/PayTMFastTag-FuelIO-Translator/pull/5
